version: '3.1'

services:
  rabbitmq:
    image: 'rabbitmq:3.13-management-alpine'
    ports:
      - '15672:15672'
      - '5672:5672'
    labels:
      NAME: 'rabbitmq'

  api-gateway:
    image: 'api-gateway:latest'
    ports:
      - '8083:8083'

  photo-management:
    image: 'photo-management-image:latest'
    ports:
      - '8081:8081'
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - rabbitmq

  photo-upload:
    image: 'photo-upload-image:latest'
    ports:
      - '8082:8082'
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - rabbitmq