apiVersion: v1
kind: Service
metadata:
  name: user-management-service
spec:
  type: ClusterIP
  selector:
    app: user-management-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
