apiVersion: v1
kind: Service
metadata:
  name: photo-management-service
spec:
  type: ClusterIP
  selector:
    app: photo-management-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
