apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.4
          ports:
            - containerPort: 8080
          command: ["kc.sh", "start", "-c", "/opt/jboss/keycloak/standalone/configuration/standalone.xml"]
