apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: rositsanikolova/auth-service:latest  # Replace with the actual image path
          ports:
            - containerPort: 8084
          env:
            # Keycloak variables
            - name: KEYCLOAK_USERNAME
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              value: "admin"
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: "http://keycloak:8080"  # Adjust to the Keycloak service endpoint
            - name: KEYCLOAK_RESOURCE
              value: "inspocloud"
            - name: KEYCLOAK_REALM
              value: "inspocloud"
            - name: KEYCLOAK_CREDENTIALS_SECRET
              value: "pJ2UfRApXmHzKfk2WCLTrAKya9SOrziD"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: "http://keycloak:8080/realms/inspocloud/protocol/openid-connect/certs"
            - name: KEYCLOAK_CREATE_USER_URL
              value: "http://keycloak:8080/admin/realms/inspocloud/users"

            # RabbitMQ variables
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"  # The service name for RabbitMQ within Kubernetes
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-service
  minReplicas: 1
  maxReplicas: 10  # Adjust maxReplicas based on your expected maximum load
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60  # Target CPU utilization percentage