apiVersion: v1
kind: Service
metadata:
  name: photo-upload-service
spec:
  type: ClusterIP
  selector:
    app: photo-upload-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
