name: CI for Auth Service

on:
  push:
    branches: [ "main", "development" ]
    paths:
      - '.github/workflows/auth-service-ci.yml'
      - 'auth-service/**'
  pull_request:
    branches: [ "main", "development" ]
    paths:
      - '.github/workflows/auth-service-ci.yml'
      - 'auth-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout code
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      run: |
        cd auth-service
        ./gradlew build -x test
        ls -l build/libs/
    - name: Upload JAR files
      uses: actions/upload-artifact@v2
      with:
        name: jar-files
        path: auth-service/build/libs/*.jar

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout code
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run tests
      run: |
        cd auth-service
        ./gradlew test

  docker-publish:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout code
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Download JAR files
      uses: actions/download-artifact@v2
      with:
        name: jar-files
        path: auth-service/build/libs/
    - name: List JAR files
      run: ls -l auth-service/build/libs/
    - name: Build and push Docker image
      run: |
        docker build -t rositsanikolova/auth-service:latest -f auth-service/Dockerfile auth-service/
        docker push rositsanikolova/auth-service:latest

  qodana:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
        fetch-depth: 0  # a full history is required for pull request analysis
    - name: 'Qodana Scan'
      uses: JetBrains/qodana-action@v2023.3
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
