name: CI for Photo Management Service

on:
  push:
    branches: [ "main", "development" ]
    paths:
      - '.github/workflows/photo-management-service-ci.yml'
      - 'photo-management-service/**'
  pull_request:
    branches: [ "main", "development" ]
    paths:
      - '.github/workflows/photo-management-service-ci.yml'
      - 'photo-management-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: cd photo-management-service && ./gradlew build -x test

    # New steps to build Docker image, tag and push
    - name: Build Docker image
      run: |
        docker build -t rositsanikolova/photo-management-service:latest .
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker image to DockerHub
      run: docker push rositsanikolova/photo-management-service:latest

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run tests
      run: cd photo-management-service && ./gradlew test

  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
