name: CI for Photo Management Service

on:
  push:
    branches: [ main ]
    paths:
      - 'photo-management-service/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'photo-management-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: cd photo-management-service && ./gradlew build -x test
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run tests
      run: cd photo-management-service && ./gradlew test
